/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as identity from "./identity";
export type { identity };
import type * as interfaces from "./interfaces";
export type { interfaces };
