/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ERC8004ReputationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "addTag"
      | "appendResponse"
      | "getClients"
      | "getIdentityRegistry"
      | "getLastIndex"
      | "getResponseCount"
      | "getResponses"
      | "getSummary"
      | "getValidTags"
      | "giveFeedback"
      | "identityRegistry"
      | "initialize"
      | "owner"
      | "proxiableUUID"
      | "readAllFeedback"
      | "readFeedback"
      | "removeTag"
      | "renounceOwnership"
      | "revokeFeedback"
      | "transferOwnership"
      | "upgradeToAndCall"
      | "validTag1"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeedbackRevoked"
      | "Initialized"
      | "NewFeedback"
      | "OwnershipTransferred"
      | "ResponseAppended"
      | "TagAdded"
      | "TagRemoved"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "addTag", values: [string]): string;
  encodeFunctionData(
    functionFragment: "appendResponse",
    values: [BigNumberish, AddressLike, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getClients",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIdentityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLastIndex",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getResponseCount",
    values: [BigNumberish, AddressLike, BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getResponses",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSummary",
    values: [BigNumberish, AddressLike[], string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidTags",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "giveFeedback",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "readAllFeedback",
    values: [BigNumberish, AddressLike[], string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "readFeedback",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "removeTag", values: [string]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeFeedback",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "validTag1", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addTag", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "appendResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getClients", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIdentityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResponseCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResponses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSummary", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getValidTags",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "giveFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readAllFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removeTag", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validTag1", data: BytesLike): Result;
}

export namespace FeedbackRevokedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    clientAddress: AddressLike,
    feedbackIndex: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    clientAddress: string,
    feedbackIndex: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    clientAddress: string;
    feedbackIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewFeedbackEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    clientAddress: AddressLike,
    feedbackIndex: BigNumberish,
    value: BigNumberish,
    valueDecimals: BigNumberish,
    indexedTag1: string,
    tag1: string,
    tag2: string,
    endpoint: string,
    feedbackURI: string,
    feedbackHash: BytesLike
  ];
  export type OutputTuple = [
    agentId: bigint,
    clientAddress: string,
    feedbackIndex: bigint,
    value: bigint,
    valueDecimals: bigint,
    indexedTag1: string,
    tag1: string,
    tag2: string,
    endpoint: string,
    feedbackURI: string,
    feedbackHash: string
  ];
  export interface OutputObject {
    agentId: bigint;
    clientAddress: string;
    feedbackIndex: bigint;
    value: bigint;
    valueDecimals: bigint;
    indexedTag1: string;
    tag1: string;
    tag2: string;
    endpoint: string;
    feedbackURI: string;
    feedbackHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResponseAppendedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    clientAddress: AddressLike,
    feedbackIndex: BigNumberish,
    responder: AddressLike,
    responseURI: string,
    responseHash: BytesLike
  ];
  export type OutputTuple = [
    agentId: bigint,
    clientAddress: string,
    feedbackIndex: bigint,
    responder: string,
    responseURI: string,
    responseHash: string
  ];
  export interface OutputObject {
    agentId: bigint;
    clientAddress: string;
    feedbackIndex: bigint;
    responder: string;
    responseURI: string;
    responseHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TagAddedEvent {
  export type InputTuple = [tag: string];
  export type OutputTuple = [tag: string];
  export interface OutputObject {
    tag: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TagRemovedEvent {
  export type InputTuple = [tag: string];
  export type OutputTuple = [tag: string];
  export interface OutputObject {
    tag: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ERC8004ReputationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ERC8004ReputationRegistry;
  waitForDeployment(): Promise<this>;

  interface: ERC8004ReputationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  addTag: TypedContractMethod<[tag: string], [void], "nonpayable">;

  appendResponse: TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish,
      responseURI: string,
      responseHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getClients: TypedContractMethod<[agentId: BigNumberish], [string[]], "view">;

  getIdentityRegistry: TypedContractMethod<[], [string], "view">;

  getLastIndex: TypedContractMethod<
    [agentId: BigNumberish, clientAddress: AddressLike],
    [bigint],
    "view"
  >;

  getResponseCount: TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish,
      arg3: AddressLike[]
    ],
    [bigint],
    "view"
  >;

  getResponses: TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish
    ],
    [
      [string[], string[], string[]] & {
        responders: string[];
        responseURIs: string[];
        responseHashes: string[];
      }
    ],
    "view"
  >;

  getSummary: TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddresses: AddressLike[],
      tag1: string,
      tag2: string
    ],
    [
      [bigint, bigint, bigint] & {
        count: bigint;
        summaryValue: bigint;
        summaryValueDecimals: bigint;
      }
    ],
    "view"
  >;

  getValidTags: TypedContractMethod<[], [string[]], "view">;

  giveFeedback: TypedContractMethod<
    [
      agentId: BigNumberish,
      value: BigNumberish,
      valueDecimals: BigNumberish,
      tag1: string,
      tag2: string,
      endpoint: string,
      feedbackURI: string,
      feedbackHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [identityRegistry_: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  readAllFeedback: TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddresses: AddressLike[],
      tag1: string,
      tag2: string,
      includeRevoked: boolean
    ],
    [
      [
        string[],
        bigint[],
        bigint[],
        bigint[],
        string[],
        string[],
        boolean[]
      ] & {
        clients: string[];
        feedbackIndexes: bigint[];
        values: bigint[];
        valueDecimals: bigint[];
        tag1s: string[];
        tag2s: string[];
        revokedStatuses: boolean[];
      }
    ],
    "view"
  >;

  readFeedback: TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish
    ],
    [
      [bigint, bigint, string, string, boolean] & {
        value: bigint;
        valueDecimals: bigint;
        tag1: string;
        tag2: string;
        isRevoked: boolean;
      }
    ],
    "view"
  >;

  removeTag: TypedContractMethod<[tag: string], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeFeedback: TypedContractMethod<
    [agentId: BigNumberish, feedbackIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  validTag1: TypedContractMethod<[arg0: string], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addTag"
  ): TypedContractMethod<[tag: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "appendResponse"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish,
      responseURI: string,
      responseHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getClients"
  ): TypedContractMethod<[agentId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getIdentityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLastIndex"
  ): TypedContractMethod<
    [agentId: BigNumberish, clientAddress: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResponseCount"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish,
      arg3: AddressLike[]
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResponses"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish
    ],
    [
      [string[], string[], string[]] & {
        responders: string[];
        responseURIs: string[];
        responseHashes: string[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSummary"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddresses: AddressLike[],
      tag1: string,
      tag2: string
    ],
    [
      [bigint, bigint, bigint] & {
        count: bigint;
        summaryValue: bigint;
        summaryValueDecimals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidTags"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "giveFeedback"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      value: BigNumberish,
      valueDecimals: BigNumberish,
      tag1: string,
      tag2: string,
      endpoint: string,
      feedbackURI: string,
      feedbackHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [identityRegistry_: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "readAllFeedback"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddresses: AddressLike[],
      tag1: string,
      tag2: string,
      includeRevoked: boolean
    ],
    [
      [
        string[],
        bigint[],
        bigint[],
        bigint[],
        string[],
        string[],
        boolean[]
      ] & {
        clients: string[];
        feedbackIndexes: bigint[];
        values: bigint[];
        valueDecimals: bigint[];
        tag1s: string[];
        tag2s: string[];
        revokedStatuses: boolean[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "readFeedback"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish
    ],
    [
      [bigint, bigint, string, string, boolean] & {
        value: bigint;
        valueDecimals: bigint;
        tag1: string;
        tag2: string;
        isRevoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeTag"
  ): TypedContractMethod<[tag: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeFeedback"
  ): TypedContractMethod<
    [agentId: BigNumberish, feedbackIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "validTag1"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;

  getEvent(
    key: "FeedbackRevoked"
  ): TypedContractEvent<
    FeedbackRevokedEvent.InputTuple,
    FeedbackRevokedEvent.OutputTuple,
    FeedbackRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "NewFeedback"
  ): TypedContractEvent<
    NewFeedbackEvent.InputTuple,
    NewFeedbackEvent.OutputTuple,
    NewFeedbackEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ResponseAppended"
  ): TypedContractEvent<
    ResponseAppendedEvent.InputTuple,
    ResponseAppendedEvent.OutputTuple,
    ResponseAppendedEvent.OutputObject
  >;
  getEvent(
    key: "TagAdded"
  ): TypedContractEvent<
    TagAddedEvent.InputTuple,
    TagAddedEvent.OutputTuple,
    TagAddedEvent.OutputObject
  >;
  getEvent(
    key: "TagRemoved"
  ): TypedContractEvent<
    TagRemovedEvent.InputTuple,
    TagRemovedEvent.OutputTuple,
    TagRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "FeedbackRevoked(uint256,address,uint64)": TypedContractEvent<
      FeedbackRevokedEvent.InputTuple,
      FeedbackRevokedEvent.OutputTuple,
      FeedbackRevokedEvent.OutputObject
    >;
    FeedbackRevoked: TypedContractEvent<
      FeedbackRevokedEvent.InputTuple,
      FeedbackRevokedEvent.OutputTuple,
      FeedbackRevokedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "NewFeedback(uint256,address,uint64,int128,uint8,string,string,string,string,string,bytes32)": TypedContractEvent<
      NewFeedbackEvent.InputTuple,
      NewFeedbackEvent.OutputTuple,
      NewFeedbackEvent.OutputObject
    >;
    NewFeedback: TypedContractEvent<
      NewFeedbackEvent.InputTuple,
      NewFeedbackEvent.OutputTuple,
      NewFeedbackEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ResponseAppended(uint256,address,uint64,address,string,bytes32)": TypedContractEvent<
      ResponseAppendedEvent.InputTuple,
      ResponseAppendedEvent.OutputTuple,
      ResponseAppendedEvent.OutputObject
    >;
    ResponseAppended: TypedContractEvent<
      ResponseAppendedEvent.InputTuple,
      ResponseAppendedEvent.OutputTuple,
      ResponseAppendedEvent.OutputObject
    >;

    "TagAdded(string)": TypedContractEvent<
      TagAddedEvent.InputTuple,
      TagAddedEvent.OutputTuple,
      TagAddedEvent.OutputObject
    >;
    TagAdded: TypedContractEvent<
      TagAddedEvent.InputTuple,
      TagAddedEvent.OutputTuple,
      TagAddedEvent.OutputObject
    >;

    "TagRemoved(string)": TypedContractEvent<
      TagRemovedEvent.InputTuple,
      TagRemovedEvent.OutputTuple,
      TagRemovedEvent.OutputObject
    >;
    TagRemoved: TypedContractEvent<
      TagRemovedEvent.InputTuple,
      TagRemovedEvent.OutputTuple,
      TagRemovedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
