/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC8004IdentityRegistry } from "./ERC8004IdentityRegistry";
export type { ERC8004ReputationRegistry } from "./ERC8004ReputationRegistry";
