/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC8004IdentityRegistry__factory } from "./ERC8004IdentityRegistry__factory";
export { ERC8004ReputationRegistry__factory } from "./ERC8004ReputationRegistry__factory";
